/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Emirhan
 */
public class AnaEkran extends javax.swing.JFrame {

    public static final String TXT_YOLU = "C:\\P2Oyun\\TXTDosyalar\\";
    public static final String RESIM_YOLU = "C:\\P2Oyun\\Resimler\\";
    String secilenKelime = "";
    int hataSayisi = 0;
    int gecenSaniye = 0;
    javax.swing.Timer zamanlayici;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnaEkran.class.getName());

    /**
     * Creates new form AnaEkran
     */
    public AnaEkran() {
        initComponents();
        loglariDoldur();
        skorlariDoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblResim = new javax.swing.JLabel();
        pnlKelime = new javax.swing.JPanel();
        txtHarf = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtKelime = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        lblSure = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlKelimeLayout = new javax.swing.GroupLayout(pnlKelime);
        pnlKelime.setLayout(pnlKelimeLayout);
        pnlKelimeLayout.setHorizontalGroup(
            pnlKelimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );
        pnlKelimeLayout.setVerticalGroup(
            pnlKelimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        jButton3.setText("Harf Dene");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Kelime Dene");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        lblSure.setText("Süre: 0 sn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHarf)
                            .addComponent(txtKelime, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlKelime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(lblSure, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblResim, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlKelime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(lblSure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHarf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKelime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)))
                    .addComponent(lblResim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Oyun Oynama", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Oyun Geçmişi"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("Temizle");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Eski Skorlar", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Giriş Kayıtları"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Temizle");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Logları Görüntüleme", jPanel3);

        jMenu1.setText("Oyun");

        jMenuItem1.setText("Oyuna Başla");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Oyunu Yeniden Başlat");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String girilenSifre = javax.swing.JOptionPane.showInputDialog(this, "Logları silmek için şifrenizi giriniz:");

        if (girilenSifre == null || girilenSifre.isEmpty()) {
            return;
        }

        try {
            java.io.File sifreDosyasi = new java.io.File(TXT_YOLU + "sifre.txt");
            java.util.Scanner okuyucu = new java.util.Scanner(sifreDosyasi);
            String kayitliSifre = "";
            if (okuyucu.hasNext()) {
                kayitliSifre = okuyucu.next();
            }
            okuyucu.close();

            if (girilenSifre.equals(kayitliSifre)) {
                java.io.FileWriter yazar = new java.io.FileWriter(TXT_YOLU + "log.txt");
                yazar.close();

                loglariDoldur();
                javax.swing.JOptionPane.showMessageDialog(this, "Loglar başarıyla temizlendi!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Hatalı şifre girdiniz! Temizleme işlemi iptal edildi.");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "İşlem sırasında bir hata oluştu!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String girilenSifre = javax.swing.JOptionPane.showInputDialog(this, "Skorları silmek için şifrenizi giriniz:");

        if (girilenSifre == null || girilenSifre.isEmpty()) {
            return;
        }

        try {
            java.io.File sifreDosyasi = new java.io.File(TXT_YOLU + "sifre.txt");
            java.util.Scanner okuyucu = new java.util.Scanner(sifreDosyasi);
            String kayitliSifre = "";
            if (okuyucu.hasNext()) {
                kayitliSifre = okuyucu.next();
            }
            okuyucu.close();

            if (girilenSifre.equals(kayitliSifre)) {
                java.io.FileWriter yazar = new java.io.FileWriter(TXT_YOLU + "oyunlar.txt");
                yazar.close();

                skorlariDoldur();
                javax.swing.JOptionPane.showMessageDialog(this, "Skorlar başarıyla temizlendi!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Hatalı şifre girdiniz! Temizleme işlemi iptal edildi.");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "İşlem sırasında bir hata oluştu!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        oyunuBaslat();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        oyunuBaslat();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (secilenKelime.isEmpty()) {
            return;
        }

        String hamTahmin = txtHarf.getText().trim();
        txtHarf.setText("");

        if (hamTahmin.isEmpty()) {
            return;
        }

        String tahmin = hamTahmin.toUpperCase(java.util.Locale.forLanguageTag("tr-TR"));

        char harf = tahmin.charAt(0);
        boolean bulunduMu = false;
        boolean oyunBittiMi = true;

        java.awt.Component[] bilesenler = pnlKelime.getComponents();

        for (int i = 0; i < secilenKelime.length(); i++) {
            if (secilenKelime.charAt(i) == harf) {
                bulunduMu = true;
                ((javax.swing.JLabel) bilesenler[i]).setText(String.valueOf(harf));
            }
            if (((javax.swing.JLabel) bilesenler[i]).getText().equals("*")) {
                oyunBittiMi = false;
            }
        }

        if (bulunduMu) {
            if (oyunBittiMi) {
                oyunuBitir(true);
            }
        } else {
            hataSayisi++;
            resimGuncelle();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (secilenKelime.isEmpty()) {
            return;
        }

        String hamTahmin = txtKelime.getText().trim();
        txtKelime.setText("");

        if (hamTahmin.isEmpty()) {
            return;
        }

        String tahmin = hamTahmin.toUpperCase(java.util.Locale.forLanguageTag("tr-TR"));

        if (tahmin.equals(secilenKelime)) {
            java.awt.Component[] bilesenler = pnlKelime.getComponents();
            for (int i = 0; i < secilenKelime.length(); i++) {
                ((javax.swing.JLabel) bilesenler[i]).setText(String.valueOf(secilenKelime.charAt(i)));
            }
            oyunuBitir(true);
        } else {
            hataSayisi++;
            resimGuncelle();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AnaEkran().setVisible(true));
    }

    private void loglariDoldur() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try {
            java.io.File dosya = new java.io.File(TXT_YOLU + "log.txt");
            if (dosya.exists()) {
                java.util.Scanner okuyucu = new java.util.Scanner(dosya);
                while (okuyucu.hasNextLine()) {
                    String satir = okuyucu.nextLine();
                    model.addRow(new Object[]{satir});
                }
                okuyucu.close();
            }
        } catch (Exception e) {
            System.out.println("Log dosyası okunamadı.");
        }
    }

    private void skorlariDoldur() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        try {
            java.io.File dosya = new java.io.File(TXT_YOLU + "oyunlar.txt");
            if (dosya.exists()) {
                java.util.Scanner okuyucu = new java.util.Scanner(dosya);
                while (okuyucu.hasNextLine()) {
                    String satir = okuyucu.nextLine();
                    model.addRow(new Object[]{satir});
                }
                okuyucu.close();
            }
        } catch (Exception e) {
            System.out.println("Skor dosyası okunamadı.");
        }
    }

    private void oyunuBaslat() {
        hataSayisi = 0;
        gecenSaniye = 0;
        secilenKelime = "";
        lblResim.setIcon(null);
        lblSure.setText("Süre: 0 sn");

        pnlKelime.removeAll();
        pnlKelime.setLayout(new java.awt.FlowLayout());

        java.util.ArrayList<String> kelimeListesi = new java.util.ArrayList<>();
        try {
            java.io.File dosya = new java.io.File(TXT_YOLU + "kelimeler.txt");
            java.util.Scanner okuyucu = new java.util.Scanner(dosya);
            while (okuyucu.hasNext()) {
                kelimeListesi.add(okuyucu.next().toUpperCase(java.util.Locale.forLanguageTag("tr-TR")));
            }
            okuyucu.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "kelimeler.txt bulunamadı!");
            return;
        }

        if (!kelimeListesi.isEmpty()) {
            java.util.Random rnd = new java.util.Random();
            secilenKelime = kelimeListesi.get(rnd.nextInt(kelimeListesi.size()));

            for (int i = 0; i < secilenKelime.length(); i++) {
                javax.swing.JLabel lblHarf = new javax.swing.JLabel("*");
                lblHarf.setFont(new java.awt.Font("Tahoma", 1, 36));
                pnlKelime.add(lblHarf);
            }
            pnlKelime.revalidate();
            pnlKelime.repaint();
        }

        if (zamanlayici != null) {
            zamanlayici.stop();
        }
        zamanlayici = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                gecenSaniye++;
                lblSure.setText("Süre: " + gecenSaniye + " sn");
            }
        });
        zamanlayici.start();
    }

    private void resimGuncelle() {
        if (hataSayisi <= 11) {
            javax.swing.ImageIcon ikon = new javax.swing.ImageIcon(RESIM_YOLU + hataSayisi + ".jpg");
            java.awt.Image img = ikon.getImage().getScaledInstance(lblResim.getWidth(), lblResim.getHeight(), java.awt.Image.SCALE_SMOOTH);
            lblResim.setIcon(new javax.swing.ImageIcon(img));
        }

        if (hataSayisi == 11) {
            oyunuBitir(false);
        }
    }

    private void oyunuBitir(boolean kazandiMi) {
        zamanlayici.stop();
        String sonuc = kazandiMi ? "KAZANDI" : "KAYBETTI";

        java.time.LocalDateTime simdi = java.time.LocalDateTime.now();
        java.time.format.DateTimeFormatter format = java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss");

        String kayit = simdi.format(format) + " | Süre: " + gecenSaniye + " sn | Sonuç: " + sonuc;

        try {
            java.io.File dosya = new java.io.File(TXT_YOLU + "oyunlar.txt");
            java.io.FileWriter yazar = new java.io.FileWriter(dosya, true);
            yazar.write(kayit + "\n");
            yazar.close();
        } catch (Exception e) {
            System.out.println("Skor kaydedilemedi.");
        }

        skorlariDoldur();

        if (kazandiMi) {
            javax.swing.JOptionPane.showMessageDialog(this, "TEBRİKLER! Kelimeyi bildiniz: " + secilenKelime + "\nSüre: " + gecenSaniye + " sn");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "MAALESEF ADAMI ASTINIZ! \nDoğru Kelime: " + secilenKelime + "\nSüre: " + gecenSaniye + " sn");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblResim;
    private javax.swing.JLabel lblSure;
    private javax.swing.JPanel pnlKelime;
    private javax.swing.JTextField txtHarf;
    private javax.swing.JTextField txtKelime;
    // End of variables declaration//GEN-END:variables
}
