/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Emirhan
 */
public class GirisEkrani extends javax.swing.JFrame {

    public static final String TXT_YOLU = "C:\\P2Oyun\\TXTDosyalar\\";
    public static final String RESIM_YOLU = "C:\\P2Oyun\\Resimler\\";

    int hataliGirisSayisi = 0;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GirisEkrani.class.getName());

    /**
     * Creates new form GirisEkrani
     */
    public GirisEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Şifrenizi Giriniz");

        jButton1.setText("Giriş Yap");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String girilenSifre = String.valueOf(jPasswordField1.getPassword());

        if (girilenSifre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Şifre boş olamaz!");
            return;
        }

        try {
            java.io.File dosya = new java.io.File(TXT_YOLU + "sifre.txt");

            if (!dosya.exists() || dosya.length() == 0) {
                java.io.FileWriter yazar = new java.io.FileWriter(dosya);
                yazar.write(girilenSifre);
                yazar.close();
                logKaydet("Yeni Şifre Belirlendi");
                javax.swing.JOptionPane.showMessageDialog(this, "İlk şifreniz başarıyla belirlendi ve kaydedildi!");
                oyunaGirisYap(); 
                return;
            }

            java.util.Scanner okuyucu = new java.util.Scanner(dosya);
            String kayitliSifre = "";
            if (okuyucu.hasNext()) {
                kayitliSifre = okuyucu.next();
            }
            okuyucu.close();

            if (girilenSifre.equals(kayitliSifre)) {
                oyunaGirisYap();
            } else {
                hataliGirisSayisi++;
                if (hataliGirisSayisi >= 3) {
                    javax.swing.JOptionPane.showMessageDialog(this, "3 defa hatalı şifre girdiniz! Güvenlik gereği program kapatılıyor.");
                    System.exit(0);
                } else {
                    logKaydet("Hatalı Şifre Denemesi");
                    javax.swing.JOptionPane.showMessageDialog(this, "Hatalı şifre! Kalan hakkınız: " + (3 - hataliGirisSayisi));
                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Dosya işlemi sırasında bir hata oluştu!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void logKaydet(String etiket) {
        try {
            java.io.File logDosyasi = new java.io.File(TXT_YOLU + "log.txt");
            java.io.FileWriter logYazar = new java.io.FileWriter(logDosyasi, true);

            java.time.LocalDateTime simdi = java.time.LocalDateTime.now();
            java.time.format.DateTimeFormatter format = java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss");

            logYazar.write(etiket + " - Zaman: " + simdi.format(format) + "\n");
            logYazar.close();
        } catch (Exception e) {
            System.out.println("Log yazılırken hata oluştu.");
        }
    }

    private void oyunaGirisYap() {
        try {
            logKaydet("Başarılı Giriş");

            javax.swing.JOptionPane.showMessageDialog(this, "Giriş Başarılı! Ana Ekran açılıyor...");

            new AnaEkran().setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("Giriş yapılırken hata oluştu.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GirisEkrani().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
